phpredisadmin:
  build: .
  volumes:
    ./:/src/app
  environment:
    - ADMIN_USER=admin
    - ADMIN_PASS=admin
    - REDIS_1_HOST=redis
    - REDIS_1_PORT=6379
  links:
    - redis
  ports:
    - "8099:80"

redis:
  image: redis
  command: --loglevel verbose
